## Fundamental of Data Science
### Assignment 1

#### Nithin KM 
#### CB.EN.U4CSE20342

1.	Generate a tuple from the set ["aman", "222", 777, 400.4]

In [ ]:
a = ["aman","222",777,400.4]
a[2]

777

2.	Create a dictionary of your basic data : (a) Roll No (b) Last Name (c) First Name (d) Date of birth. Print out the values and keys.

In [1]:
import numpy as np
import pandas as pd

b = np.array([(1,"R","Ram","12.12.23"),
              (2,"S","Seetha","12.3.22"),
              (3,"SJ","Laxman","31.4.21"),
              (4,"S","Arun","14.5.20")],
             dtype=[('Roll No','i4'),('Last Name','U10'),('First Name','U10'),('D.O.B','U10')])
print(b)
print(b[1])
print(b['Last Name'])

[(1, 'R', 'Ram', '12.12.23') (2, 'S', 'Seetha', '12.3.22')
 (3, 'SJ', 'Laxman', '31.4.21') (4, 'S', 'Arun', '14.5.20')]
(2, 'S', 'Seetha', '12.3.22')
['R' 'S' 'SJ' 'S']


3.	Use rand function to generate a 2-dimensional random array with seed.

In [ ]:
c=np.random.seed(2)
c=np.random.randint(low=1,high=8,size=(2,4))
c

array([[1, 6, 1, 7],
       [4, 3, 4, 1]])

4.	Generate a single random number in [0.0, 1.0]. Find the absolute value of (-1234)

In [ ]:
np.random.seed(2)
np.random.random(1)

array([0.4359949])

5.	Return a random integer N such that 20 <= N <= 90. 

In [ ]:
np.random.seed(2)
np.random.randint(low=20,high=90,size=(1))

array([60])

6.	Given a population or set[11, 12, 13,14, 15]
o	Return a 3 length list of unique elements without replacement.
o	Shuffle the above set
o	Print a random number from the set


In [ ]:
import random
bd= [11,12,13,14,15]
random.sample(bd,k=3)

[13, 11, 15]

7.	Write the text "The King is Dead, Long Live The King" on to a file in your hard drive; read and print the text.

In [ ]:
lines = ["The King is Dead, Long Live The King"]
with open('readme.txt', 'w') as f:
    f.writelines(lines)
with open('readme.txt','r') as g:
    print(g.read())

The King is Dead, Long Live The King


In [ ]:
random.shuffle(b)
bd

[11, 12, 13, 14, 15]

8.	Create an illustrative function to demonstrate use of: if, elif and else (b) for, while, break and continue. 

In [ ]:
num = 3.4
if num > 0:
    print("Positive number")
elif num == 0:
    print("Zero")
else:
    print("Negative number")

Positive number


In [ ]:
list = []
for val in "string":
    if val == "i":
        break
    elif val == "t":
      continue
    list.append(val)
    print(val)

i=0
while i < len(a):
  print(list[i])
  i += 1
print("The end")

s
r
The end


In [ ]:
random.choice(b)

14

9.	Given a string "The King is Dead, Long Live The King" 


*   Print the complete string
*   Print first character of the string
*   Print characters starting from 3rd to 5th
*   Print string starting from 3rd character
*   Split the words


In [ ]:
with open('readme.txt','r') as g:
    s=g.read()
print(s)
print(s[0])
print(s[2:4])
print(s[2:])
print(s.split())

The King is Dead, Long Live The King
T
e 
e King is Dead, Long Live The King
['The', 'King', 'is', 'Dead,', 'Long', 'Live', 'The', 'King']


10.	An array can be created from a list:  Create an array from a list comprising of numbers 1,4,5,8 (treat them as floats).Slice the above array to display first and second elements

In [ ]:
list1 = [1,4,5,8]
floats = [float(x) for x in list1]
print(floats[0])
print(floats[1])

1.0
4.0


11.	Arrays can be multidimensional. Create a two-dimensional array of (1,2,3) and (4,5,6).

In [ ]:
list2=np.array([[1,2,3],[4,5,6]])
list2

array([[1, 2, 3],
       [4, 5, 6]])

12.	Array slicing works with multiple dimensions in the same way as usual, applying each slice specification as a filter to a specified dimension. Consider two-dimensional array of (1,2,3) and (4,5,6).

*   Slice and display the 2nd row.

In [ ]:
print(list2[1,:])

[4 5 6]


* Write code to display as array([2., 5.]) 

In [ ]:
cpslice = [list2[0,1].astype(np.float32)]
cpslice.append(list2[1,1].astype(np.float32))
print(cpslice)

[2.0, 5.0]



*   Find the length of the array.


In [ ]:
list2.size

6

13.	Arrays can be reshaped using tuples that specify new dimensions. Turn a ten-element one-dimensional array into a two-dimensional one whose first axis has five elements and whose second axis has two elements. Obtain the transpose of the array

In [ ]:
onedtotwod = np.arange(0,10)
onedtotwod


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
d2 = onedtotwod.reshape(2,5)
d2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
np.transpose(d2)

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

14.	Create an array from a list of 1,2 and 3.

In [ ]:
list23 = [1,2,3]
print(list23)
d = np.array(list23)

print(d)

[1, 2, 3]
[1 2 3]


15.	Fill an array [1,2,3] with a single value [9,9,9]. 

In [ ]:
temp = np.array([1,2,3])
temp[temp>0]=9
print(temp)

[9 9 9]


16.	Sum the elements of array [2,4,5].

In [ ]:
np.sum(temp)

27

17.	Give the products of array [77,74,75]

In [ ]:
np.prod(temp)

729

18.	Given an array [2,1,9,1,2,22,1,1,4,55,6,2,56]. Find mean, variance, max, min, argmin, median, argmax and standard deviation.

In [ ]:
arr18 = np.array([2,1,9,1,2,22,1,1,4,55,6,2,56])
arr18.mean()

12.461538461538462

In [ ]:
arr18.var()

367.32544378698225

In [ ]:
arr18.max()

56

In [ ]:
arr18.min()

1

In [ ]:
arr18.argmin()

1

In [ ]:
np.median(arr18)

2.0

In [ ]:
arr18.argmax()

12

In [ ]:
arr18.std()

19.165736192147232

19.	Extract unique elements from an array: [1, 1, 4, 5, 5, 5, 7] and sort it.

In [ ]:
arr = np.array([1, 1, 4, 5, 5, 5, 7])
set1 = set(arr)
sorted(set1)

[1, 4, 5, 7]

20.	Find dot product of two arrays [1, 2, 3]and [0, 1, 1]. 

In [ ]:
t1 = np.array([1, 2, 3])
t2 = np.array([0, 1, 1])
np.dot(t1, t2, out=None)

5

21.	Find the eigenvalues and eigenvectors of matrix A.

In [ ]:
t21 = np.array([[2,-12],
               [1,-5]])
w,v=np.linalg.eig(t21)
print(w)
print(v)

[-1. -2.]
[[0.9701425  0.9486833 ]
 [0.24253563 0.31622777]]
